apiVersion: v1
kind: Service
metadata:
  name: tour-package-fe-service
spec:
  selector:
    app: tour-package-fe
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP